### PR TITLE
docker: update to use php8

### PR DESCRIPTION
**Pull request by mattburchett**

### CODE REVIEW

**Comment by mattburchett** [comment]
@AndrewPaglusch This should fix the issues that's causing Dependabot to fail it's checks.

**Comment by modem7** [comment]
@mattburchett - Would it be worthwhile editing the original notes with "Fixes #61" so it auto closes when merged?

**Comment by AndrewPaglusch** [comment]
I just tested this. FlashPaper seems to be working well on PHP8. Closes #61 (not sure if this will work from a comment)

**Comment by AndrewPaglusch** [comment]
Whoops. Maybe I should merge first

**Review by AndrewPaglusch — APPROVED** [review]

**Pull request merged**
