### PR TITLE
Fixed warnings & deprecated issues

### PR DESCRIPTION
**Pull request by dehlirious**
Solution: Turn ${var} to {$var} , instead of using $json use false.

```
PHP message: PHP Deprecated:  Using ${var} in strings is deprecated, use {$var} instead in index.php on line 102; 
PHP message: PHP Deprecated:  Using ${var} in strings is deprecated, use {$var} instead in index.php on line 112; 
PHP message: PHP Deprecated:  Using ${var} in strings is deprecated, use {$var} instead in index.php on line 113; 
PHP message: PHP Warning:  Undefined variable $json in index.php on line 27"

```

### CODE REVIEW

**Comment by AndrewPaglusch** [comment]
@dehlirious Thanks for the PR! I'll reply back here after we've had a chance to review it.

**Comment by dehlirious** [comment]
> @dehlirious Thanks for the PR! I'll reply back here after we've had a chance to review it.

Awesome. Any chance you'd open a discussions section on this repo?

**Review by AndrewPaglusch — APPROVED** [review]
Tested locally. Working good

**Comment by AndrewPaglusch** [comment]
@dehlirious I forgot to mention: I opened discussions! Thanks for the suggestion

**Pull request merged**
